### ISSUE TITLE
CalypsoExtensionService crash on android 6 and prior

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse/keyple-util-java-lib#25]
Hello Team,
Calypso extension is unusable on android 6 and prior. When instantiating the extension, a DataJsonSerializer is created which in turn creates a SimpleDateFormat.
https://github.com/eclipse/keyple-util-java-lib/blob/4743f9ac68fb49ae5fa0c2fe2b69f6e59cf00633/src/main/java/org/eclipse/keyple/core/util/json/DateJsonSerializer.java#L38
This line throws an exception
` Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
                                                                                                    	at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:314)
                                                                                                    	at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:303)
                                                                                                    	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:356)
                                                                                                    	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:249)`

Android documentation suggests that the 'X' format is supported in API 23 but it's not the case.
http://androidxref.com/6.0.1_r10/xref/libcore/luni/src/main/java/java/text/SimpleDateFormat.java#211
http://androidxref.com/6.0.1_r10/xref/libcore/luni/src/main/java/java/text/SimpleDateFormat.java#320

I don't know exactly where this format is used but it probably can safely be replaced by **_"yyyy-MM-dd'T'HH:mm:ss.SSSZ"_**

Thank you for your help

**Comment by jeanpierrefortune** [comment]
Hi Aghilas,

I have pushed a fix which you can see at this commit: e0dba48b9a5cee0c81e809f84f31172eb75bf7f4.
This fix maintains the same date text format, but it no longer uses the "X" format specifier.
Can you try using the latest 2.3.1-SNAPSHOT version and let me know if you encounter any issues?

Regards

**Comment by amessara-billettiqueservices** [comment]
The crash is fixed @jeanpierrefortune. Thank you very much for the quick response.

**Comment by amessara-billettiqueservices** [comment]
My bad @jeanpierrefortune I had some local changes with a work around the crash that I forgot to clean.
There is the same issue in _**CalendarJsonAdapter**_
https://github.com/eclipse/keyple-util-java-lib/blob/e0dba48b9a5cee0c81e809f84f31172eb75bf7f4/src/main/java/org/eclipse/keyple/core/util/json/CalendarJsonAdapter.java#L42

**Comment by jeanpierrefortune** [comment]
Hi Aghilas,

I have made the necessary changes to fix the issue in `CalendarJsonAdapter` too. You can view the changes in this commit: d7f7df1e0649e60132a2c4bc6ae167745c11a6b0.

Please use the latest 2.3.1-SNAPSHOT version to test these changes.

Let me know if you encounter any further issues.

Regards

**Comment by andrei-cristea** [comment]
Hello Aghilas,

We plan to release on Monday, September 11, 2023.

Best regards

**Comment by andrei-cristea** [comment]
Hello Aghilas,

The version `2.3.1` is now available.

Best regards
